# Generated by Django 4.1.7 on 2023-10-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cajas', '0002_alter_cajas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodega', to='cajas.bodegas'),
        ),
        migrations.AlterField(
            model_name='usuariobodega',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuariobod', to=settings.AUTH_USER_MODEL),
        ),
    ]
