# Generated by Django 4.1.7 on 2023-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_alter_usuariobodega_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='observacion',
            field=models.CharField(default='consignacion dia 2023-10-24', max_length=300),
        ),
    ]
