# Generated by Django 4.2.6 on 2023-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_cajas_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='observacion',
            field=models.CharField(default='consignacion dia 2023-11-01', max_length=300),
        ),
    ]
