# Generated by Django 4.2.6 on 2024-02-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_bodegas_centrocosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='observacion',
            field=models.CharField(default='consignacion dia 2024-02-14', max_length=300),
        ),
    ]
