# Generated by Django 4.2.6 on 2024-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0008_alter_cajas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='observacion',
            field=models.CharField(default='consignacion dia 2024-02-15', max_length=300),
        ),
    ]
