# Generated by Django 4.0.3 on 2022-05-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del beneficio a crear', max_length=100, unique=True)),
                ('detalle', models.CharField(help_text='detalles de que es el benefecion ejemplo tiempo para ti es un dia al año libre', max_length=500)),
                ('condiciones', models.CharField(help_text='es la descripcion de que tiene que cumplir el empleado para poder aplicar', max_length=500)),
                ('catidadDeSolicitudes', models.IntegerField(help_text='numero de solicitudes que puede hacer la persona de este beneficio')),
                ('estado', models.IntegerField(default=1, help_text='estado 1:activo , 0:inactivo ')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodepermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('es_beneficio', models.IntegerField(default=0, help_text=' 1:es tipo beneficio , 0:no lo es ')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('salida', models.TimeField(blank=True, null=True)),
                ('reingreso', models.TimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.IntegerField(default=0, help_text='estado 0:solicitado , 1:aprobado , 2: rechazado')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='permisos.beneficios')),
                ('tipopermiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permisos.tipodepermiso')),
                ('usuarioaprobacion', models.ForeignKey(blank=True, db_column='ids', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ids', to=settings.AUTH_USER_MODEL)),
                ('usuariodecreacion', models.ForeignKey(blank=True, db_column='emails', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to=settings.AUTH_USER_MODEL)),
                ('usuariodepermiso', models.ForeignKey(db_column='usernames', on_delete=django.db.models.deletion.PROTECT, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('ver_permisos_de_todos', 'ver_permisos_de_todos'), ('aprobar_permisos', 'aprobar_permisos')],
            },
        ),
    ]
