# Generated by Django 4.0.3 on 2022-05-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_alter_permisos_reingreso_alter_permisos_salida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': [('ver_permisos_de_todos', 'ver_permisos_de_todos'), ('aprobar_permisos', 'aprobar_permisos'), ('salida_y_entrada', 'salidad_y_entrada')]},
        ),
    ]
