# Generated by Django 4.0.5 on 2022-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_permisos_fechaaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='fechacreacion',
            field=models.DateTimeField(null=True),
        ),
    ]
