# Generated by Django 4.1.7 on 2023-09-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permisos', '0007_alter_permisos_fechaaprobacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEncargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.ForeignKey(db_column='encargado', on_delete=django.db.models.deletion.PROTECT, related_name='encargado', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
