# Generated by Django 4.2.6 on 2024-02-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permisos', '0008_usuarioencargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=1, help_text='estado 1:activo , 0:inactivo')),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuariohorarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosPorteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaentrada', models.TimeField()),
                ('horasalida', models.TimeField()),
                ('totalhoras', models.IntegerField()),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuariohorariosporteria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
