# Generated by Django 4.2.6 on 2024-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_alter_horariosporteria_totalhoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioPorteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horarios', models.ManyToManyField(db_column='horarios', related_name='horarios', to='permisos.horariosporteria')),
            ],
        ),
    ]
