# Generated by Django 4.2.6 on 2024-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0011_calendarioporteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosporteria',
            name='fecha',
        ),
        migrations.AddField(
            model_name='horariosporteria',
            name='tipo',
            field=models.IntegerField(default=1, help_text='tipo 1:horario , 2: horario 2'),
        ),
    ]
