# Generated by Django 4.2.6 on 2024-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0012_remove_horariosporteria_fecha_horariosporteria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosporteria',
            name='diasemana',
            field=models.IntegerField(default=0, help_text='0:lunes , 1:martes , 2:miercoles , 3:jueves , 4:viernes , 5:sabado , 6:domingo'),
        ),
    ]
