# Generated by Django 4.2.6 on 2024-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0013_horariosporteria_diasemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosporteria',
            name='total_horas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
