# Generated by Django 4.2.6 on 2024-02-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0014_horariosporteria_total_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosporteria',
            name='total_horas',
        ),
    ]
