# Generated by Django 4.2.6 on 2024-02-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0015_remove_horariosporteria_total_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosporteria',
            name='totalhoras',
            field=models.FloatField(default=0, help_text='total de horas'),
        ),
    ]
