# Generated by Django 4.2.6 on 2024-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0016_alter_horariosporteria_totalhoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioporteria',
            name='semana',
            field=models.IntegerField(default=0, help_text='semana 1:semana 1 , 2:semana 2 , 3:semana 3 , 4:semana 4'),
        ),
    ]
