# Generated by Django 4.1.3 on 2023-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convenios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("fecha_inicial", models.DateField()),
                ("fecha_final", models.DateField()),
                (
                    "activo",
                    models.IntegerField(
                        default=0, help_text="estado 0: activo , 1: inactivo"
                    ),
                ),
                ("archivo", models.FileField(upload_to="pdfs/")),
            ],
        ),
    ]
