# Generated by Django 4.1.3 on 2023-03-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0003_promociones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promociones",
            name="descripcion",
            field=models.TextField(max_length=10000),
        ),
    ]
