# Generated by Django 4.1.3 on 2023-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0004_alter_promociones_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="convenios",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="convenios",
            name="telefono",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
