# Generated by Django 4.1.7 on 2023-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_convenios_email_convenios_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineasCelularesContratadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=50)),
                ('estado', models.IntegerField(default=0, help_text='estado 0: activo , 1: inactivo')),
                ('pertenece', models.CharField(max_length=200)),
                ('quien_paga', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, max_length=10000, null=True)),
                ('valor', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'lineas_celulares_contratadas',
            },
        ),
    ]
