# Generated by Django 4.1.7 on 2023-04-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_lineascelularescontratadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineascelularescontratadas',
            options={'permissions': [('ver_lineas_celulares_contratadas', 'Ver lineas celulares contratadas')]},
        ),
    ]
