# Generated by Django 4.1.7 on 2023-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_alter_lineascelularescontratadas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineascelularescontratadas',
            name='operador',
            field=models.CharField(default='Claro', max_length=200),
        ),
    ]
