# Generated by Django 4.1.7 on 2023-08-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_lineascelularescontratadas_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
