# Generated by Django 4.1.7 on 2023-09-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_promociones_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promociones',
            options={'permissions': [('puede_editar_promociones', 'Puede editar promociones')]},
        ),
    ]
